mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day2;
mod day20;
mod day21;
mod day22;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod utils;

fn main() {
    day1::execute();
    day2::execute();
    day3::execute();
    day4::execute();
    day5::execute();
    day6::execute();
    day7::execute();
    day8::execute();
    day9::execute();
    day10::execute();
    day11::execute();
    day12::execute();
    day13::execute();
    day14::execute();
    day15::execute();
    day16::execute();
    day17::execute();
    day18::execute();
    day19::execute();
    day20::execute();
    day21::execute();
    day22::execute();
}
