mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day2;
mod day20;
mod day21;
mod day22;
mod day23;
mod day24;
mod day25;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;

fn main() {
    println!("Day  1: {}", day1::execute());
    println!("Day  2: {}", day2::execute());
    println!("Day  3: {}", day3::execute());
    println!("Day  4: {}", day4::execute());
    println!("Day  5: {}", day5::execute());
    println!("Day  6: {}", day6::execute());
    println!("Day  7: {}", day7::execute());
    println!("Day  8: {}", day8::execute());
    println!("Day  9: {}", day9::execute());
    println!("Day 10: {}", day10::execute());
    println!("Day 11: {}", day11::execute());
    println!("Day 12: {}", day12::execute());
    println!("Day 13: {}", day13::execute());
    println!("Day 14: {}", day14::execute());
    println!("Day 15: {}", day15::execute());
    println!("Day 16: {}", day16::execute());
    println!("Day 17: {}", day17::execute());
    println!("Day 18: {}", day18::execute());
    println!("Day 19: {}", day19::execute());
    println!("Day 20: {}", day20::execute());
    println!("Day 21: {}", day21::execute());
    println!("Day 22: {}", day22::execute());
    println!("Day 23: {}", day23::execute());
    println!("Day 24: {}", day24::execute());
    println!("Day 25: {}", day25::execute());
}
